version: '2'
services:
    clockin-app:
        image: clockin
        external_links:
            - clockin-mysql:mysql
            - clockin-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/clockin?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    clockin-mysql:
        extends:
            file: mysql.yml
            service: clockin-mysql
    clockin-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: clockin-elasticsearch
